### PR TITLE
Updated Pagefile Resource to fix test/set when passed a size not divi…

### PR DESCRIPTION
**Pull request by bushe**
Updated Pagefile Resource to fix test/set when passed a size not divisible by 1MB

### CODE REVIEW

**Comment by bushe** [comment]
This failed on "install-module pester", what should my next steps be?

**Comment by dlwyatt** [comment]
You've installed the OneGet module, but not PowerShellGet.  From what I've seen, most people just use Chocolatey to install Pester in an appveyor build, since their build agents have Chocolatey installed already.  For example:  https://github.com/RamblingCookieMonster/Wait-Path/blob/master/appveyor.yml

**Comment by dlwyatt** [comment]
Ah, I had assumed that you changed something in the yaml file that caused the failure.  Maybe it's the oneget.zip file that has changed over time; if it used to contain PowerShellGet as part of the same distribution back in the previews, that would explain the current state.

I'll sort it out.  :)

**Comment by dlwyatt** [comment]
I've updated the yaml file in the master branch, but you may need to push another commit to this PR (or rebase it or whatever) in order to trigger a new build.

**Comment by bushe** [comment]
Closing to retry for the updated build checks

**Pull request closed without merging**
